version: '3.8'

services:
  autoprune:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: autoprune
    restart: unless-stopped
    network_mode: host
    env_file:
      - .env
    
    volumes:
      - /mnt/app-pool/config/autoprune/state:/app/state
