version: '3.8'

services:
  autoprune:
    build:
      context: https://github.com/InfamousMorningstar/guardian.git#main
      dockerfile: Dockerfile
    container_name: autoprune
    restart: unless-stopped
    network_mode: host
    env_file:
      - /mnt/app-pool/config/autoprune/.env
    
    volumes:
      - /mnt/app-pool/config/autoprune/state:/app/state
